version: '3.7'
services:
  node-app:
    build: gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'

  postgres:
    image: postgres:12.0-alpine
    container_name: pstg-container
    ports:
      - '5432:5432'
#    для Windows 10 Pro на Mac не работает:
#    volumes:
#      - ./data_postgres:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  mysql:
    image: mysql:8.0.18
    container_name: mysql-container
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass